INSERT ALL
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (1, 'sunnyday12', 1001, 5, TO_DATE('2024-01-03', 'YYYY-MM-DD'), '먹던 제품에서 이걸로 바꿨습니다. 효능이 좋길 바랍니다.', TO_DATE('2023-12-25', 'YYYY-MM-DD'), 'review1.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (2, 'blueSky88', 1049, 4, TO_DATE('2024-09-23', 'YYYY-MM-DD'), '마그네슘을 처음 사용해봤는데, 패키지에 담긴 양이 많지 않아서 실험적으로 이 패키지를 선택했어요', TO_DATE('2024-09-10', 'YYYY-MM-DD'), 'review2.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (3, 'dreamer7', 1025, 5, TO_DATE('2024-09-16', 'YYYY-MM-DD'), '철분은 소홀하기 쉬운 영양소 이기도 해서 매일 잘 챙기고 있습니다. 떨어지면 재구매 예정입니다.', TO_DATE('2024-09-03', 'YYYY-MM-DD'), 'review3.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (4, 'powerGamer2023', 1047, 4, TO_DATE('2024-08-17', 'YYYY-MM-DD'), '가격대비 품질 좋고 성분함량 충분해요. 면역력도 올라가고 모발 손톱에도 좋다고 해서 다른 영양제랑 매일 먹고있어요.', TO_DATE('2024-08-02', 'YYYY-MM-DD'), 'review4.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (5, 'starfish99', 1084, 5, TO_DATE('2024-06-11', 'YYYY-MM-DD'), '루테인이 눈 건강을 유지하는데 효능이 있다고 해서 부모님께 사드렸어요.', TO_DATE('2024-05-26', 'YYYY-MM-DD'), 'review5.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (6, 'kingroyal23', 1070, 4, TO_DATE('2024-08-14', 'YYYY-MM-DD'), '구입 후 한달 간 복용한 결과, 피로감이 줄고 피부톤이 밝아진 느낌을 받아 재구매했습니다.', TO_DATE('2024-08-01', 'YYYY-MM-DD'), 'review6.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (7, 'happyBee_04', 1048, 5, TO_DATE('2024-02-10', 'YYYY-MM-DD'), '케토 비타민이라고 해서 선택해봤어요 품질 성분은 믿을 수 있는 캘리포니아 제품이에요', TO_DATE('2024-01-29', 'YYYY-MM-DD'), 'review7.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (8, 'coolcat001', 1076, 4, TO_DATE('2024-06-24', 'YYYY-MM-DD'), '퀄리티도 성분도 높고, 피부의 탄력이 좋아지는게 몸으로 느껴집니다. 아주 좋은 보충제입니다.', TO_DATE('2024-06-12', 'YYYY-MM-DD'), 'review8.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (9, 'rainbowstar24', 1177, 4, TO_DATE('2024-08-10', 'YYYY-MM-DD'), '평소에는 하루 한알씩 면역력이 떨어질때나 감기 올려고 할때마다 두알씩 먹고 있는데 효과 직빵입니다.', TO_DATE('2024-08-02', 'YYYY-MM-DD'), 'review9.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (10, 'silentKnight15', 1197, 5, TO_DATE('2024-06-23', 'YYYY-MM-DD'), '크기가 새끼손가락 손톱보다 작고 반들반들한 재질이라 목넘김이 편하고 아이도 잘 먹어요.', TO_DATE('2024-06-10', 'YYYY-MM-DD'), 'review10.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (11, 'magicBox77', 1085, 4, TO_DATE('2024-05-25', 'YYYY-MM-DD'), '저렴한 가격에 품질과 성분이 좋은 구성입니다. 나이가 들 수록 콜라겐의 중요성을 느껴서 구매했습니다.', TO_DATE('2024-05-10', 'YYYY-MM-DD'), 'review11.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (12, 'fastrunner5', 1125, 4, TO_DATE('2024-07-25', 'YYYY-MM-DD'), '위가 안좋고 소화가 안되서 헛트름나고 배에 가스차고 해서 이것저것 먹어보다가 이 제품을 먹고 속이 너무 편해져서 놀랐어요.', TO_DATE('2024-07-12', 'YYYY-MM-DD'), 'review12.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (13, 'technoKing09', 1105, 5, TO_DATE('2024-06-10', 'YYYY-MM-DD'), '유익균 농도도 만족하고, 먹기에 크기도 불편하지 않아요', TO_DATE('2024-06-01', 'YYYY-MM-DD'), 'review13.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (14, 'wildTiger12', 1130, 4, TO_DATE('2024-09-02', 'YYYY-MM-DD'), '품질과 성분이 좋고 무엇보다 고함량에 적당한 크기로 운동하는 사람에겐 좋을거 같습니다.', TO_DATE('2024-08-19', 'YYYY-MM-DD'), 'review14.png')
    INTO Review (Review_No, User_ID, Sup_id, Rating, Review_Date, Content, Intake_Date, Review_Img) 
    VALUES (15, 'neofuture01', 1132, 3, TO_DATE('2024-08-16', 'YYYY-MM-DD'), '냄새가 조금 나긴 하지만 밀크시슬 잘 먹고 있습니다.', TO_DATE('2024-08-02', 'YYYY-MM-DD'), 'review15.png')
SELECT 1 FROM DUAL;